name: food_truck_app
description: A Flutter food truck finder and management app
publish_to: 'none'
version: 1.64.0+116

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Core dependencies
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Location services
  geolocator: ^10.1.0
  location: ^5.0.3
  permission_handler: ^11.0.1
  
  # Photo upload and image handling
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  image: ^4.1.3
  
  # UI and navigation
  url_launcher: ^6.2.1
  flutter_spinkit: ^5.2.0
  
  # State management
  provider: ^6.1.1
  
  # Networking and caching
  dio: ^5.3.2
  cached_network_image: ^3.3.0
  
  # Additional dependencies for features
  google_maps_flutter: ^2.5.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  table_calendar: ^3.0.9
  webview_flutter: ^4.4.2
  
  # Firebase services
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  firebase_analytics: ^10.7.4
  firebase_performance: ^0.9.3+8
  
  # Network and connectivity
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
